### ISSUE TITLE
I cannot find the file named split.py under the directories KolektorSDD and KolektorSDD2？

### ISSUE THREAD

**Issue by Qiqigeww** [jnhwkim/orthoad#3]
I cannot find the file named split.py under the directories KolektorSDD and KolektorSDD2, how should I handle this error message？

**Comment by jnhwkim** [comment]
I'm afraid I can't follow you. Could you elaborate on your problem?

**Comment by Qiqigeww** [comment]
When I run the code, the following error occurs：
FileNotFoundError: [Errno 2] No such file or directory: 'kolektor-training-splits/split.pyb'

**Comment by jnhwkim** [comment]
In `README.md`, I mentioned, `For the Kolektor Surface-Defect Dataset (KolektorSDD), please visit [this site](http://www.vicos.si/Downloads/KolektorSDD) and [this site](http://www.vicos.si/Downloads/KolektorSDD2).`

These sites seem to provide the splits still through [KolektorSDD-training-splits.zip](https://data.vicos.si/datasets/KSDD/KolektorSDD-training-splits.zip). Could you check those official websites for the datasets?

**Comment by Qiqigeww** [comment]
OK,I‘ve seen it, thank you.
